# Get all comments for post
GET http://localhost:3000/api/posts/79cc980c-3e48-4598-8607-0a29f0a837cf/comments HTTP/1.1

###


# Create a new comment for post
POST http://localhost:3000/api/posts/79cc980c-3e48-4598-8607-0a29f0a837cf/comments HTTP/1.1
Content-Type: application/json

{
  "message": "This is text",
  "userId": "65990102bb965b742900ba59"
}

###
